id = "dracula"
name = "Dracula"
version = "0.7.3"
schema_version = 1
authors = ["Ben Hamment <fisix1@gmail.com>"]
description = "Official Dracula theme for Zed"
repository = "https://github.com/dracula/zed"
